Header and banner
hapo-chidl/Hapo_Learn_Boostrap pull request #1
Opened 2020-08-05 09:48 UTC by hapo-chidl

2020-08-05 09:57 UTC, hapo-hieupm requested changes

2020-08-05 09:57 UTC, hapo-hieupm commented on .gitignore
> +Scss/variable+mixin.css.map
thay bằng scss/*.css

2020-08-05 09:57 UTC, hapo-hieupm commented on Scss/header.scss
> +      &:hover {
bậc lớn hơn 3

2020-08-05 09:57 UTC, hapo-hieupm commented on Scss/header.scss
> +      img {
bậc lớn hơn 3

2020-08-05 09:57 UTC, hapo-hieupm commented on Scss/header.scss
> +      &:hover {
bậc lớn hơn 3

2020-08-05 09:57 UTC, hapo-hieupm commented on Scss/variable+mixin.scss
> +$bg-color:  #B2D235;
tên biến để snake_case

2020-08-05 09:57 UTC, hapo-hieupm commented on Scss/variable+mixin.scss
> +@mixin font ($font-family, $color, $font-size){
tên biến để snake_case

2020-08-05 09:57 UTC, hapo-hieupm commented on Scss/variable+mixin.scss
> +@mixin text-stoke ($a,$b,$c){
thêm dấu cách sau dấu phẩy

2020-08-05 09:57 UTC, hapo-hieupm commented on index.html
> +    </script>
script để xuống dưới

2020-08-05 09:57 UTC, hapo-hieupm commented on Scss/variable+mixin.scss
> +@mixin size-img ($width,$height){
tên hàm để camelCase

2020-08-05 10:11 UTC, hapo-hoangtv commented on Scss/reponsive.scss
> +    }
cái include để xuống dưới cùng nhé

2020-08-05 10:11 UTC, hapo-hoangtv commented on Scss/reponsive.scss
> +        @include text-stoke(UTM BryantLG, 0.1px, $color);
đây cũng thế

2020-08-05 10:12 UTC, hapo-nghialt commented on .gitignore
> +Scss/variable+mixin.css.map
nên thay tất cả bằng `scss/*.css*`

2020-08-05 10:12 UTC, hapo-nghialt commented on Scss/header.scss
> +      color: #505353 !important;
tại sao cần `!important`?

2020-08-05 10:12 UTC, hapo-nghialt commented on Scss/header.scss
> +      @include text-stoke(UTM BryantLG, 1px, $text-color);
đặt tên biến theo `snake_case`

2020-08-05 10:32 UTC, hapo-hieupm approved these changes
LGTM

2020-08-05 12:26 UTC, hapo-nghialt approved these changes
LGTM

2020-08-06 01:53 UTC, hapo-datnd commented on Scss/header.scss
> +    @include button($bg-color, 70px, 377px, 35px);
Đặt biến `snake_case` em nhá

2020-08-06 01:53 UTC, hapo-datnd commented on Scss/reponsive.scss
> +        color: $bg-color !important;
Đây nữa

2020-08-06 01:54 UTC, hapo-datnd commented on Scss/variable+mixin.scss
> +    border-radius: $border-radius;
@hapo-chidl Đây nữa e

2020-08-06 01:54 UTC, hapo-datnd commented on Scss/variable+mixin.scss
> +@mixin textStoke ($a, $b, $c){
Sao đặt tên biến thế này em @@. @hapo-chidl

2020-08-06 03:22 UTC, hapo-datnd approved these changes

2020-08-06 06:25 UTC, merged